version: '3'
services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  hextorgb:
    image: hextorgb
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hextorgb.rule=PathPrefix(`/hextorgb`)"
      - "traefik.http.routers.hextorgb.middlewares=hextorgb-stripprefix"
      - "traefik.http.middlewares.hextorgb-stripprefix.stripprefix.prefixes=/hextorgb"